accounts/urls.py
from django.contrib import admin
from django.urls import path 
from accounts import views 



urlpatterns = [
    path('register',views.register, name='register'),
    path('login',views.login, name='login'),
    path('logout',views.logout, name='logout'),
    path('profile',views.profile, name='profile'),
    
   
]

diary/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
]+ static(settings.MEDIA_URL , document_root =settings.MEDIA_ROOT )

home/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.home ,name='home'),
    path('create',views.create ,name='create'),
    path('<slug>',views.full,name="full"),
]

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(upload_to='media/',blank=True,default='')
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:70] + "..."    

accounts/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse 
from django.contrib.auth.models import User , auth
from home.models import Blog



# Create your views here.
def register(request):
    if request.method == 'POST':
        first_name = request.POST["f-name"]
        last_name = request.POST["l-name"]
        email = request.POST["email"]
        username = request.POST["u-name"]
        password1 = request.POST["p1"]
        password2 = request.POST["p2"]
        if password1 == password2:
            if User.objects.filter(username=username).exists():
                return HttpResponse('<h1>user exisits</h1>') 
            elif User.objects.filter(email=email).exists():
                return HttpResponse('<h1>user exisits</h1>')
            else:
                user = User.objects.create_user(username=username,password=password1,email=email,first_name=first_name,last_name=last_name)
                user.save()
                print("user saved")
                return redirect('/accounts/login')
        else:
            return HttpResponse('<h1>password not matching</h1>')
       
    else:
        return render(request,"register.html")


def login(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            
            return HttpResponse("<h1>INvalid</h1>")
    else:
        return render(request,"login.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

def profile(request):
    
    d = Blog.objects.all()
    dicti = {'dests':d}
    return render(request,"profile.html",dicti)

    

home/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse 
from . models import Blog
from . form import *

# Create your views here.


def home(request):
    blog = Blog.objects.all().order_by('date')
    return render(request,"home.html",{'blog':blog})

def full(request,slug):
    #return HttpResponse(slug)
    article = Blog.objects.get(slug=slug)
    return render(request,"article.html",{'article':article})


def create(request):
    if request.method == 'POST': 
        form = CreateBlog(request.POST, request.FILES) 
  
        if form.is_valid(): 
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()

            return redirect('home:home') 
    else:

        form = CreateBlog() 

  
    return render(request,"create.html",{'form':form})

templates/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Article</title>
</head>
<body>
    <h1>{{article.title}}</h1>
    <img src="{{article.thumb.url}}">
    <h3>{{article.body}}</h3>
    {{article.date}}
</body>
</html>

templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create</title>
</head>
<body>
    <h1>Create here</h1>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %} 

    {{ form.as_p }} 
    <input type="submit" value="create">
</form>
</body>
</html>

templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Blogify</title>
  </head>
  <body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Blogify</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="/create">Create</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/accounts/login">Login</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="/accounts/register">signup
                  </a>
                  <li class="nav-item">
                    <a class="nav-link" href="/accounts/logout">Logout
                    </a>
                </li>
                
              </ul>
            </div>
          </nav>
          
    </div>
    <div class="articles">
      {% for blog in blog %}
        <div class="article">
          <h1><a href="{% url 'home:full' slug=blog.slug %}">{{blog.title}}</a></h1>
          <h3>{{blog.snippet}}</h3><br>
          {{blog.date}}
        </div>
      {% endfor %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login page</title>
</head>
<body>
    <h1>Welcome please login</h1>
    <form axtion="login" method="POST" >
        {% csrf_token %}
        <input type="text" name="username" placeholder="username"><br>
        <input type="password" name="password" placeholder="password"><br>
        <input type="submit">
    </form>
  
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration page</title>
</head>
<body>
   
    <h1>Join us - Register here</h1>
    <form method="POST" action="register">
        {% csrf_token %}
        <input type="text" name="f-name" placeholder="First name"><br>
        <input type="text" name="l-name" placeholder="Last name"><br>
        <input type="email" name="email" placeholder="Email"><br>
        <input type="text" name="u-name" placeholder="username"><br>
        <input type="password" name="p1" placeholder="p1"><br>
        <input type="password" name="p2" placeholder="p2"><br>
        <input type="submit">
    </form>
</body>
</html>